### ISSUE TITLE
[BUG] Worker and API pods fail when S3 bucket not in us-east-1.

### ISSUE THREAD

**Issue by amendez-alphavisionoption** [BorisPolonsky/dify-helm#101]
**Describe the bug**
S3_REGION defaults to 'us-east-1' which will cause api and worker pod to crash if externalS3 enabled and bucket region is not in us-east-1.

**To Reproduce**
In the helm chart:
...
      externalS3:
        enabled: true
        endpoint: "https://<BUCKET_NAME>.s3.<REGION_BESIDES_US_EAST_1>.amazonaws.com"
        accessKey: "<ACCESS_KEY>"
        secretKey: "<SECRET_KEY>"
        useSSL: true
        bucketName: "<BUCKET_NAME>"
        rootPath: ""
        useIAM: false
        iamEndpoint: ""
...

**Expected behavior**
The dify and worker configmap should have the S3_REGION variable set from the chart, but it is instead hardcoded in https://github.com/BorisPolonsky/dify-helm/blob/fdccbfc1ebcb4d4ad169ab2b2a0f7f63dc6293ad/charts/dify/templates/config.tpl#L157.

**Desktop (please complete the following information):**
 - Chart Version: 0.21.0
 - Helm version (from helm version) Latest
 - Dify version 0.14.1

**Comment by BorisPolonsky** [comment]
Noted. A quick workaround for this would be applying extra environment variables through `api.extraEnv` and `worker.extraEnv`. Meanwhile we'll make this option configurable in `values.yaml`
