### ISSUE TITLE
dify-helm-0.14.1 faild deploy dify version >=0.3.8

### ISSUE THREAD

**Issue by JeromeLiuLly** [BorisPolonsky/dify-helm#11]
dify-helm vaild to dify console url.
example: https://github.com/langgenius/dify/blob/main/api/config.py
```
self.CONSOLE_API_URL = get_env('CONSOLE_URL') if get_env('CONSOLE_URL') else get_env('CONSOLE_API_URL')
self.CONSOLE_WEB_URL = get_env('CONSOLE_URL') if get_env('CONSOLE_URL') else get_env('CONSOLE_WEB_URL')
```
helm value.yaml need to add those key。

**Comment by JeromeLiuLly** [comment]
success way :
helm upgrade -i my-release --set 'externalWeaviate.enabled=true' --set 'externalWeaviate.endpoint=http://weaviate.dify.svc.cluster.local' --set 'api.url.api=https://api.dify.linknext.io' --set 'api.url.console=https://cloud.dify.linknext.io' --set 'api.url.app=https://web.dify.linknext.io' --set 'redis.replica.replicaCount=1' --set 'image.api.tag=0.3.9' --set 'image.web.tag=0.3.9' --set 'weaviate.image.tag=1.18.4' --set 'api.persistence.persistentVolumeClaim.existingClaim=pvc-nfs-dify-api' --set 'proxy.log.persistence.persistentVolumeClaim.existingClaim=pvc-nfs-dify-proxy-log' --set 'postgresql.primary.persistence.storageClass=nfs-client' --set 'postgresql.readReplicas.persistence.storageClass=nfs-client' --set 'weaviate.storage.storageClassName=nfs-client' --set 'redis.master.persistence.existingClaim=pvc-nfs-dify-redis-master' --set 'redis.replica.persistence.existingClaim=pvc-nfs-dify-redis-replica' --set 'web.extraEnv[0].name=EDITION' --set 'web.extraEnv[0].value=SELF_HOSTED' --set 'web.extraEnv[1].name=CONSOLE_URL' --set 'web.extraEnv[1].value=https://web.dify.linknext.io' --set 'web.extraEnv[2].name=APP_URL' --set 'web.extraEnv[2].value=https://web.dify.linknext.io' --set 'api.extraEnv[0].name=CHECK_UPDATE_URL' --set 'api.extraEnv[0].value=https://updates.dify.ai' -n dify .

**Comment by BorisPolonsky** [comment]
## Memo
Difference in [docker-compose.yaml](https://github.com/langgenius/dify/compare/0.3.1...0.3.8#diff-89fafc265c1fa601cf2364b20be83308031335fda9467fcf3249d5ec1c0c8172) between `0.3.1` and `0.3.8`

**Comment by BorisPolonsky** [comment]
@JeromeLiuLly Please try out this [patch](https://github.com/BorisPolonsky/dify-helm/tree/b37eef6af660d65dd56a2e394f7e710fe2576c6f) and see if it's solved.

**Comment by BorisPolonsky** [comment]
We've completed compatibility support in this [release](https://github.com/BorisPolonsky/dify-helm/releases/tag/dify-0.16.0)
