### ISSUE TITLE
is there any plan for the rebasing with latest Dify release?

### ISSUE THREAD

**Issue by gaolitao** [BorisPolonsky/dify-helm#20]

**Comment by BorisPolonsky** [comment]
Yes, but I'm currently very busy and haven't caught up with the latest version yet. Could you elaborate and list what are the incompatible parts in the current version of helm chart?

**Comment by gaolitao** [comment]
Thanks, what i can see are that the env variables like: 

> CONSOLE_API_URL
The backend URL of the console API, used to concatenate the authorization callback. If empty, it is the same domain. Example: https://api.console.dify.ai
CONSOLE_WEB_URL
The front-end URL of the console web, used to concatenate some front-end addresses and for CORS configuration use. If empty, it is the same domain. Example: https://console.dify.ai
SERVICE_API_URL
Service API Url, used to display Service API Base Url to the front-end. If empty, it is the same domain. Example: https://api.dify.ai
APP_API_URL

listed https://docs.dify.ai/getting-started/install-self-hosted/environments

**Comment by BorisPolonsky** [comment]
> Thanks, what i can see are that the env variables like:
> 
> > CONSOLE_API_URL
> > The backend URL of the console API, used to concatenate the authorization callback. If empty, it is the same domain. Example: https://api.console.dify.ai
> > CONSOLE_WEB_URL
> > The front-end URL of the console web, used to concatenate some front-end addresses and for CORS configuration use. If empty, it is the same domain. Example: https://console.dify.ai
> > SERVICE_API_URL
> > Service API Url, used to display Service API Base Url to the front-end. If empty, it is the same domain. Example: https://api.dify.ai
> > APP_API_URL
> 
> listed https://docs.dify.ai/getting-started/install-self-hosted/environments

Such incompatibilities should have been fixed in [this version](https://github.com/BorisPolonsky/dify-helm/pull/15).

**Comment by BorisPolonsky** [comment]
I got stuck [setting up k8s development environment](https://github.com/docker/for-win/issues/13873) with docker desktop recently, so no progress so far. Any help on this issue would be appreciated.

**Comment by BorisPolonsky** [comment]
@gaolitao Please give [this version](https://github.com/BorisPolonsky/dify-helm/pull/27) a shot
