### ISSUE TITLE
INSTALLATION FAILED

### ISSUE THREAD

**Issue by ken209** [BorisPolonsky/dify-helm#36]
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: [unknown object type "nil" in ConfigMap.data.APP_API_URL, unknown object type "nil" in ConfigMap.data.CONSOLE_API_URL]

k8s version : 1.23

**Comment by BorisPolonsky** [comment]
We could not replicate the issue with default `Values.yaml`. Please specify the `Values.yaml` you've applied and the installation command as well.

**Comment by TruongNguyen5395** [comment]
I have the same problem but don't know what the cause is

**Comment by BorisPolonsky** [comment]
> I have the same problem but don't know what the cause is

@TruongNguyen5395 Please submit a new issue with steps to replicate.
