### ISSUE TITLE
[BUG]should add quote to QDRANT_CLIENT_TIMEOUT/consoleApi/appApi in config.tpl

### ISSUE THREAD

**Issue by kaktos** [BorisPolonsky/dify-helm#44]
error when creating "worker-config.yaml": ConfigMap in version "v1" cannot be handled as a ConfigMap: json: cannot unmarshal number into Go struct field ConfigMap.data of type string

**Comment by BorisPolonsky** [comment]
Could you please elaborate and confirm if it's fixed in https://github.com/BorisPolonsky/dify-helm/pull/45?
