### ISSUE TITLE
[BUG] rpc error: code = InvalidArgument desc = ControllerPublishVolume Volume capability is not compatible:

### ISSUE THREAD

**Issue by ip2cloud** [BorisPolonsky/dify-helm#47]
In Linode K8s/

AttachVolume.Attach failed for volume "pvc-XXXXXXX" : rpc error: code = InvalidArgument desc = ControllerPublishVolume Volume capability is not compatible: volume_id:"2808205-XXXXXXXX" node_id:"444444" volume_capability:<mount:<fs_type:"ext4" > access_mode:<mode:MULTI_NODE_MULTI_WRITER > > volume_context:<key:"storage.kubernetes.io/csiProvisionerIdentity" value:"444444-555555-linodebs.csi.linode.com" >

**Comment by BorisPolonsky** [comment]
This case is similar to https://github.com/BorisPolonsky/dify-helm/issues/8. If you want to use "local storage" for sharing data among `api` and `worker`, which are running on separate nodes, you have to create storage that support `ReadWriteMany` and define proper storage class through `values.yaml`. The log you provided suggest that `ext4`, which doesn't suit this purpose, were provisioned through the Container Storage Interface.

Alternatively you may also use externalS3 instead of "local volume".

**Comment by ip2cloud** [comment]
Hello. Thanks for getting back to us. The case is that I am running on Linode's kubernetes service and it does not allow 2 pods to access the same disk. The disk is not the node that the 2 pods are on, but both cannot access it. Can I create a disk for each pod? If so.. where do I change this in the .yaml and which yaml do I change. Can you help me?

**Comment by BorisPolonsky** [comment]
You need to consult linode support to find out the kind of storage class that supports `ReadWriteMany`.

**Comment by ip2cloud** [comment]
I checked with Linode and the Kubernetes service does not actually support ReadWriteMany. :(

What I found was an option to create an NFS server in the same kubernetes network and change the class. (Same solution as EKS). https://startup2scalable.com/2024/02/read-write-many-volumes-on-lke-with-nfs/

But what do you suggest? S3 or NFS?

How do I integrate S3 into Helm?

**Comment by BorisPolonsky** [comment]
> I checked with Linode and the Kubernetes service does not actually support ReadWriteMany. :(
> 
> What I found was an option to create an NFS server in the same kubernetes network and change the class. (Same solution as EKS). https://startup2scalable.com/2024/02/read-write-many-volumes-on-lke-with-nfs/
> 
> But what do you suggest? S3 or NFS?
> 
> How do I integrate S3 into Helm?

Generally speaking, object storage (e.g. S3) demands less expense than file systems. You may check pricing from your cloud service provider for that.
I assume that you are familiar with altering helm configuration via `values.yaml` (e.g. `helm install -f <your-values.yaml>`). To use externalS3, fill in [this section](https://github.com/BorisPolonsky/dify-helm/blob/3778d884878dbe2e3c932f425f56968d6058ef20/charts/dify/values.yaml#L2479-L2492) and set `externalS3.enable=true`

**Comment by ip2cloud** [comment]
Thanks @BorisPolonsky ! Resolved with S3 Linode Service

**Comment by jalberto** [comment]
@ip2cloud may I ask how you resolved it? Even with `externalS3.enable=true` `daemon` is trying to create a local volume
