### ISSUE TITLE
无法安装dify服务

### ISSUE THREAD

**Issue by JeromeLiuLly** [BorisPolonsky/dify-helm#6]
Error: template: dify/templates/worker-config.yaml:6:6: executing "dify/templates/worker-config.yaml" at <include "dify.worker.config" .>: error calling include: template: dify/templates/config.tpl:89:4: executing "dify.worker.config" at <include "dify.vectordb.config" .>: error calling include: template: dify/templates/config.tpl:223:40: executing "dify.vectordb.config" at <eq .clusterIP "None">: error calling eq: incompatible types for comparison

**Comment by BorisPolonsky** [comment]
> Error: template: dify/templates/worker-config.yaml:6:6: executing "dify/templates/worker-config.yaml" at <include "dify.worker.config" .>: error calling include: template: dify/templates/config.tpl:89:4: executing "dify.worker.config" at <include "dify.vectordb.config" .>: error calling include: template: dify/templates/config.tpl:223:40: executing "dify.vectordb.config" at <eq .clusterIP "None">: error calling eq: incompatible types for comparison

https://github.com/langgenius/dify/issues/393#issuecomment-1595691386
