### ISSUE TITLE
Helm lint error

### ISSUE THREAD

**Issue by silversteak** [BorisPolonsky/dify-helm#67]
**Describe the bug**
Testing the helm chart of dify so that I can use it. I did a
`helm lint charts/dify` to check the charts. 

**To Reproduce**
1. Downloaded dify charts. 
2. Installed helm 2.17 in local
3. Did `helm lint charts/dify`

**Expected behavior**
```
helm lint charts/dify 
==> Linting charts/dify
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: render error in "dify/templates/worker-config.yaml": template: dify/templates/worker-config.yaml:6:6: executing "dify/templates/worker-config.yaml" at <include "dify.worker.config" .>: error calling include: template: dify/templates/config.tpl:97:3: executing "dify.worker.config" at <include "dify.vectordb.config" .>: error calling include: template: dify/templates/config.tpl:240:44: executing "dify.vectordb.config" at <eq .clusterIP "None">: error calling eq: invalid type for comparison

Error: 1 chart(s) linted, 1 chart(s) failed
```

**Desktop (please complete the following information):**
 - OS: Mac 14.4.1
 - Helm version (from helm version) : 2.17.1
 - Dify version - 0.6.3

**Additional context**

**Comment by BorisPolonsky** [comment]
This helm chart requires Helm v3.12+

**Comment by silversteak** [comment]
```
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /Users/sr181o/.kube/config
==> Linting charts/dify
[INFO] Chart.yaml: icon is recommended
[WARNING] /k8s-helm/charts/dify: chart directory is missing these dependencies: postgresql,redis,weaviate

1 chart(s) linted, 0 chart(s) failed

```

I had updated my helm to helm3.14, now its showing the above WARNING. 

I have a doubt since am pretty much new to helm charts.

Is there any way to change helm3.14 charts to helm2 charts ?..... 

Just asking out of curiosity.
