### ISSUE TITLE
[BUG] Error when setting externalAzureBlobStorage to true

### ISSUE THREAD

**Issue by Onoshun-HWS** [BorisPolonsky/dify-helm#68]
This is my first time reporting a bug on github, so please forgive the poor quality.

**Describe the bug**
Setting the next value to true will result in an error.
```
externalAzureBlobStorage:
  enabled: true
```
Because there is no condition for this.
.Values.externalAzureBlobStorage.enabled

dify-helm / charts / dify / templates/ api-deployment
```
volumeMounts:
        {{- if not .Values.externalS3.enabled }}
        - name: app-data
```

I believe that these conditions will resolve the error.
```
volumeMounts:
        {{- if not (or .Values.externalS3.enabled .Values.externalAzureBlobStorage.enabled) }}
        - name: app-data
```

**To Reproduce**
1. `
externalAzureBlobStorage:
  enabled: true
`
2. helm upgrade dify dify/dify -f values.yaml
3. `Error: UPGRADE FAILED: cannot patch "dify-api" with kind Deployment: Deployment.apps "dify-api" is invalid: spec.template.spec.containers[0].volumeMounts[0].name: Not found: "app-data" && cannot patch "dify-worker" with kind Deployment: Deployment.apps "dify-worker" is invalid: spec.template.spec.containers[0].volumeMounts[0].name: Not found: "app-data"`

**Desktop (please complete the following information):**
 - OS: [e.g. ubuntu 22.04 on WSL2]
 - Helm version: version.BuildInfo{Version:"v3.14.2", GitCommit:"", GitTreeState:"clean", GoVersion:"go1.21.6"}
 - Dify version: 
   - CHART VERSION: 0.20.0   
   - APP VERSION: 0.6.3

**Comment by BorisPolonsky** [comment]
Thanks for identifying the bug and providing a solution. Please check out this [PR](https://github.com/BorisPolonsky/dify-helm/pull/690) and see if it solves the problem.

**Comment by BorisPolonsky** [comment]
[Fixed](https://github.com/BorisPolonsky/dify-helm/releases/tag/dify-0.20.1)
