### ISSUE TITLE
Why can't I see the prompt for version updates

### ISSUE THREAD

**Issue by YYyp99** [BorisPolonsky/dify-helm#73]
![image](https://github.com/BorisPolonsky/dify-helm/assets/120240141/f9d7165a-e48e-4901-8cf1-d362099ea9cf)
After I deployed it, version 0.0.0 remained displayed and I did not receive any update notifications

**Comment by BorisPolonsky** [comment]
Plsease refer to `CHECK_UPDATE_URL` in [Official Document](https://docs.dify.ai/getting-started/install-self-hosted/environments)
