### ISSUE TITLE
How do you define the ingress paths if the proxy is not enabled?

### ISSUE THREAD

**Issue by Anvesh-Gummalas** [BorisPolonsky/dify-helm#75]
Hello, please advise on the ingress paths to the respective backend services in case the proxy container is not enabled. Thanks.

**Comment by BorisPolonsky** [comment]
Hello there. `Ingress` defined by this chart routes external traffic to `proxy` for simplicity purpose. If you wish to bypass `proxy` components, it's advised to deploy and manage ingress and corresponding routing rules separately. In this way the app maintainers shall supervise `dify` itself and leave external traffic management to the cluster administrators.

**Comment by Anvesh-Gummalas** [comment]
Hello. Used external ingress and declared the paths - /console/api, /api, /v1, /files, / to respective api and web services as found in the nginx proxy config. Thanks
