### ISSUE TITLE
[BUG] environment name of api key in sandbox is wrong

### ISSUE THREAD

**Issue by kaktos** [BorisPolonsky/dify-helm#76]
The environment name of api key in `credentials.tpl` line 120 shouldn't be 'CODE_EXECUTION_API_KEY', it's API_KEY.

**Comment by BorisPolonsky** [comment]
Noted.

**Comment by BorisPolonsky** [comment]
There's a lot to be overhauled so it won't be merged into `master` asap. But please do review https://github.com/BorisPolonsky/dify-helm/commit/6985f7c0f46a2af8f8e9c3d249cd30a6f712db51 in `dev` branch if possible. @kaktos

**Comment by kaktos** [comment]
ok
