### ISSUE TITLE
Please update to 0.6.11 or latest version of Dify

### ISSUE THREAD

**Issue by Shomu-Maersk** [BorisPolonsky/dify-helm#78]
**Describe the bug**
We saw there are a lot of bugs resolved in the latest version of Dify. 
With new features added as of 0.6.11 https://github.com/langgenius/dify/releases/tag/0.6.11

**Expected behavior**
Update to 0.6.11 or the latest Dify version

**Screenshots**

**Desktop (please complete the following information):**
 - Helm version (from helm version) [e.g. v3.12.0]
 - Dify version [e.g. 0.6.3]

**Additional context**
Compare vs https://github.com/langgenius/dify/compare/0.6.3...0.6.11

**Comment by Nordpolar** [comment]
That would be amazing especially to use tools like workflow as a tool

**Comment by BorisPolonsky** [comment]
@Shomu-Maersk https://github.com/BorisPolonsky/dify-helm/pull/81

**Comment by Shomu-Maersk** [comment]
@BorisPolonsky, any update on merging it to master branch :)

**Comment by ericshiu** [comment]
HI @BorisPolonsky  any update ?

**Comment by BorisPolonsky** [comment]
It's in the `master` branch now. Welcome to the contributor list everybody.
