### ISSUE TITLE
[BUG] Run chart-releaser-action tag_name  already_exists 

### ISSUE THREAD

**Issue by ericshiu** [BorisPolonsky/dify-helm#85]
Error: error creating GitHub release dify-0.20.1: 

POST https://api.github.com/repos/BorisPolonsky/dify-helm/releases: 422 Validation Failed [{Resource:Release Field:tag_name Code:already_exists Message:}]

**Comment by BorisPolonsky** [comment]
So why bother doing this given that `0.20.1` is already released? https://github.com/BorisPolonsky/dify-helm/releases/tag/dify-0.20.1

**Comment by ericshiu** [comment]
Hi @BorisPolonsky  
Yesterday, the master image version was updated to 0.6.11.
 An error occurred during the execution of the github action. I expected that you would update the version to 0.20.2?

**Comment by BorisPolonsky** [comment]
> Hi @BorisPolonsky Yesterday, the master image version was updated to 0.6.11. An error occurred during the execution of the github action. I expected that you would update the version to 0.20.2?

It's expected as we are not planning for a new release for now. We would optimize the workflow triggering logic soon.

**Comment by ericshiu** [comment]
Thanks !
