### ISSUE TITLE
Update to Dify v0.7.2?

### ISSUE THREAD

**Issue by ralberts** [BorisPolonsky/dify-helm#88]
Just curious - is there anything blocking from us upgrading to the latest dify?  I could help if it is useful, I just wasn't sure if there are known issue with the latest and using your helm.

Thanks again for making this!  It's been so great!

**Comment by BorisPolonsky** [comment]
All you need is to edit your own version of `.Values.yaml` and substitute image tags.

**Comment by SoumyaMaitra** [comment]
0.7.2 seems to be working ok with only tag changes as @BorisPolonsky mentioned. 
repository: langgenius/dify-api & repository: langgenius/dify-web =>  tag: "0.7.2"
repository: langgenius/dify-sandbox ==> tag: "0.2.6"

**Comment by ralberts** [comment]
Ok, great!!! Thank you all so much!
