### ISSUE TITLE
ServiceAccount specification in the Helm chart

### ISSUE THREAD

**Issue by japan4415** [BorisPolonsky/dify-helm#91]
Currently, the Helm chart included in the dify-helm repository does not have a field for specifying the ServiceAccount in the Deployment resource. As a result, users who wish to use a ServiceAccount must manually modify the chart.

In particular, in cloud environments such as AWS, it is common to attach IAM roles to pods using a ServiceAccount, allowing for secure access management. 
Additionally, in environments where service meshes like Istio are used, specifying a ServiceAccount is recommended to apply policies and authentication to each pod. In Istio, a ServiceAccount is used to generate pod-level identities, which are then leveraged for access control and traffic management within the service mesh, making this feature critical.

Previously, there was an issue requesting the addition of a ServiceAccount for AWS access, which was rejected with the reason that the repository maintainers did not wish to accommodate specific conditions. 
However, the ability to specify a ServiceAccount is not limited to AWS, but is a basic feature used broadly in Kubernetes environments. Considering its importance for general use cases such as with Istio, adding this capability to the Helm chart would benefit a wide range of users.

I would appreciate your consideration of this proposal. Thank you.

**Comment by BorisPolonsky** [comment]
Thank you for your contribution and the resourceful explanation on user cases. This feature is expected to be merged after we have tested it.

**Comment by japan4415** [comment]
@BorisPolonsky 
yay! Thank you.
I'll fix your review.
