### ISSUE TITLE
No readiness probe for dify api or dify web

### ISSUE THREAD

**Issue by masoodamunchen** [BorisPolonsky/dify-helm#93]
There is no readiness probe for dify api and dify web and doesn't seem a way to be able to override it. Any reason for not having the readiness probe for dify api or web for an example? I am using argo cd manifest.

Best regards

**Comment by BorisPolonsky** [comment]
Thanks for your reply. Could you elaborate and suggest which api in `dify` suits such purpose?

**Comment by BorisPolonsky** [comment]
Please evaluate if this feature suits this purpose. https://github.com/BorisPolonsky/dify-helm/pull/94 @masoodamunchen
