### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Shomu-Maersk** [BorisPolonsky/dify-helm#95]
**Describe the bug**
If you upgrade the Dify version to the latest like 0.9.xx in values and keep the other pod version the same the system is unstable for some time. I think the helm charts need to be updated to 0.9 xx so that people can get the benefit on model o1 etc.

Bugs found with this configuration was
1.  internal server errors shown
2. Knowledge upload failure 
3. slowness in response

**To Reproduce**
1. Go to values and only change the tags for app/web as 0.9.x
4. Deploy the helm chatrts 
5. Observe the system 

**Expected behavior**
The system should be stable in higher versions as well.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux 
 - Helm version v3.11.3
 - Dify 08.3/0.9.x

**Comment by Shomu-Maersk** [comment]
Any update please?

**Comment by BorisPolonsky** [comment]
Tested and things work with the following configuration
- `langgenius/dify-api:0.9.2`
- `langgenius/dify-web:0.9.2`
- `langgenius/dify-web:0.2.9`
We don't think any of the problem state above were related to the definition of the chart itself. Closing this issue.

**Comment by LinkMaq** [comment]
I tested on the latest 0.13.1 version whitout any changes ,and dify is working well.
